version: 2

sources:
  - name: contoso_bronze
    database: contoso
    schema: bronze
    tables:
      - name: dim_account
      - name: dim_channel
      - name: dim_currency
      - name: dim_customer
      - name: dim_date
      - name: dim_employee
      - name: dim_entity
      - name: dim_geography
      - name: dim_machine
      - name: dim_outage
      - name: dim_product
      - name: dim_product_category
      - name: dim_product_subcategory
      - name: dim_promotion
      - name: dim_sales_territory
      - name: dim_scenario
      - name: dim_store
      - name: fact_exchange_rate
      - name: fact_inventory
      - name: fact_it_machine
      - name: fact_itsla
      - name: fact_online_sales
      - name: fact_sales
      - name: fact_sales_quota
      - name: fact_strategy_plan
      - name: my_first_dbt_model
      - name: my_second_dbt_model
